### ISSUE TITLE
Fronttiin käyttäjän tietojen muokkausnäkymä

### ISSUE THREAD

**Issue by UllaMontonen** [TeamRed-Ohjelmistoprojekti2/TimeManagement#106]
Näkymä, missä käyttäjä voi muokata omia tietoja, lisäys myös naviin. Käyttäjä voi muokata etunimeä, sukunimeä, salasanaa. Tässä vaiheessa ei voi päivittää s.postia.

**Comment by jinblo** [comment]
Käyttäjätunnusta voi muuttaa. Kun PUT palauttaa uuden tokenin -> ota se vastaan
