### ISSUE TITLE
Appuser PUT metodin päivitys

### ISSUE THREAD

**Issue by UllaMontonen** [TeamRed-Ohjelmistoprojekti2/TimeManagement#111]
Pitää tarkistaa että käyttäjän id joka sitä tekee niin mätsää muokattavan käyttäjän id:tä. Ettei voi muokata jonkun muun tietoja. Käyttäjä voi muokata etunimeä, sukunimeä, salasanaa. Tässä vaiheessa ei voi päivittää käyttäjänimeä.

**Comment by kristinLu** [comment]
Duplicate
