### ISSUE TITLE
30.4. issues jatkokehitysideat tiiminä tehdään

### ISSUE THREAD

**Issue by UllaMontonen** [TeamRed-Ohjelmistoprojekti2/TimeManagement#160]
Lisätä jatkokehityksen ideoista taskit (issues)

**Comment by jinblo** [comment]
- Suljetut user storyt
- "Avoimen" kirjauksen teko (merkintä kun aloittaa työnteon)

**Comment by UllaMontonen** [comment]
- AgGrid elementin teko responsiiviseksi mobiilille (esim. osa vain näkyy ja jos kääntää puhelinta niin sitten näkyy kaikki vaihtoehdot)

**Comment by UllaMontonen** [comment]
- Näkyviin käytetyt tunnit yhteensä projektikohtaisesti
- Etusivulle diagrammi näyttämään mihin projekteihin käyttäjä on aikaansa käyttänyt (%)
- Projektiin lisätylle käyttäjälle tieto, että hänet on lisätty projektille ja hänen tulee tämä lisäys hyväksyä
- Filtteröinti toiminnallisuus entry sivulle, esim. voi valita minkä ajankohdan tunnit haluaa nähdä
- Mahdollisuus merkitä projektit valmiiksi, jolloin ne siirtyvät omaan osioon
- Mahdollisuus tulostaa yhteenveto tietyn projektin tunneista tietyltä ajankohdalta laskutusta varten (owner kaikki tunnit, user vain omat tunnit)

**Comment by UllaMontonen** [comment]
Frontin ja bäkin kansiorakenteen selkeytys
