### ISSUE TITLE
ReadMe tunnettujen virheiden dokumentointi

### ISSUE THREAD

**Issue by UllaMontonen** [TeamRed-Ohjelmistoprojekti2/TimeManagement#161]
Jos on virheitä projektissa niin niistä maininta

**Comment by s0ina** [comment]
Katsotaan tätä vielä yhdessä, kirjataan kuitenkin ylös jos virheitä tulee vastaan viimeisen sprintin aikana.

**Comment by UllaMontonen** [comment]
Readme dokkarissa Testaus ja esiin tulleet virheet -osiossa nyt tämä teksti: End-to-end testien lisäksi toteutimme myös manuaalista testaamista tiimin voimin. Testauksessa ei tullut ilmi virheitä koodin toiminnallisuuteen liittyen.

Jos löytyy vielä virheitä niin tuo osio tulee muuttaa.

**Comment by UllaMontonen** [comment]
Yksi virhe löydetty ja dokumentoitu: Kun käyttäjä lisää projektille uutta käyttäjää ja saman session aikana hän haluaakin poistaa käyttäjän, jota ei kuitenkaan ole vielä lisätty projektille, ja painaa tallenna-nappia, niin lisätty käyttäjä lisätään projektin tietoihin roolilla null. Bäkki ei osaa poistaa käyttäjää listasta, jossa sitä ei ole. Kun projektin avaa uudelleen niin käyttäjänimi näkyy listassa, mutta käyttäjän rooli on tyhjänä. Tämä projekti näkyy myös lisätylle käyttäjälle ja hän voi lisätä projektille tuntikirjauksia.
