### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by jinblo** [TeamRed-Ohjelmistoprojekti2/TimeManagement#165]
[ProjectRESTController](https://github.com/TeamRed-Ohjelmistoprojekti2/TimeManagement/blob/main/TimeManagementBE/src/main/java/TeamRed/TimeManagementBE/web/ProjectRESTController.java)

**Comment by Samwes13** [comment]
- Koodi on helposti ymmärttevä ja muotoilto selkeästi, mikä helpottaa ylläpitoa.
- Jokainen REST-endpoint käsittelee virheet ja palauttaa HTTP-vastauksen, jossa on hyvä virhekoodi ja virheviesti.
-  End pointit tarkistavat käyttäjän käyttöoikeudet ennen toiminnallisuuksien suorittamista.  Esim 'removeProject' kohdassa.
