### ISSUE TITLE
Dokumentointi: sprinti1 osalta

### ISSUE THREAD

**Issue by jinblo** [TeamRed-Ohjelmistoprojekti2/TimeManagement#27]

**Comment by UllaMontonen** [comment]
- Tietokantakaavio
- Kehitysympäristöt (bäkki ja frontti)
- Api rajapinta (listaus ja omat sivut, esim. katso kuva)

![Image](https://github.com/TeamRed-Ohjelmistoprojekti2/TimeManagement/assets/92970187/61788b0c-2bfe-4b0c-98f0-7749e1ede9be)
