### ISSUE TITLE
User Story 12: Käyttäjänä haluan lisätä projektin muille käyttäjille erilaisia rooleja, jotta voin määritellä kuka näkee ja mitäkin

### ISSUE THREAD

**Issue by UllaMontonen** [TeamRed-Ohjelmistoprojekti2/TimeManagement#4]
admin voi tehdä kaikkea ja lisätä käyttäjiä projekteille. Admin voi muokata muiden käyttäjien rooleja.
user voi lisätä kirjauksia, muokata omia kirjauksiaan, sekä poistaa niitä.
viewer pystyy vain lukemaan tietoja ja tulostamaan, ei muuttamaan tai poistamaan.

**Comment by jinblo** [comment]
Ehdotus roolien nimeämisestä epäselvyyksien välttämiseksi: Owner, Collaborator/Member, Viewer
