### ISSUE TITLE
Katselmointipyyntö

### ISSUE THREAD

**Issue by jinblo** [TeamRed-Ohjelmistoprojekti2/TimeManagement#74]
Työaikakirjauksen lisääminen. 

[TimeManagementFE\src\components\AddEntry.jsx](https://github.com/TeamRed-Ohjelmistoprojekti2/TimeManagement/blob/development/TimeManagementFE/src/components/AddEntry.jsx)

saveEntry ja projects importoitu EntryList.jsx 

Toimivuus testattu manuaalisesti :D

**Comment by Samwes13** [comment]
- Selkeä ja muotoiltu hyvin
- #42.rivi##const [open, setOpen] = useState(false);# Koodin pätkä voisi olla ylhäällä muiden kanssa.
- Entry alustuksen voisi tehdä omaan erilliseen olioon, jotta sen voi laittaa setEntryn kautta haluttuun tilaan. Tällä hetkellä sama koodi toistuu kahdesti.
- Dialogin voisi siirtää omaan komponenttiin.
